const DB_NAME = `social_media_db`;
const MAX_POOL_SIZE = 10;
const SERVER_SELECTION_TIMEOUT_MS = 5000;
const SOCKET_TIMEOUT_MS = 45000;

export { DB_NAME, MAX_POOL_SIZE, SERVER_SELECTION_TIMEOUT_MS, SOCKET_TIMEOUT_MS };
